services:
  api:
    container_name: python-container
    tty: true
    stdin_open: true
    build: 
      context: .
      dockerfile: ./api/dockerfile
    volumes:
    - ./src:/app/
    ports:
    - "5000:5000"
    networks:
    - app_network
    
  db:
    image: mysql
    container_name: mysql-container
    build: ./db/dockerfile
    environment:
      LANG: C.UTF-8
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: dbdata
    volumes:
    - ./db/dbdata/:/var/lib/mysql
    ports:
    - "3306:3306"
    networks:
    - app_network

  backend-api:
    container_name: backend-api-container
    build: 
      context: ./backend_api
      dockerfile: dockerfile
    ports:
    - "5555:5555"
    networks:
      - app_network
    
    
networks:
    app_network:
      driver: bridge